# Library 불러오기

In [2]:
import numpy as np

## 1차원 배열 만들기

In [3]:
list1 = [1, 3, 5, 7, 9]

In [59]:
arr1 = np.array(list1)
arr1
# np.array : numpy에서 제공하는 배열을 만들어주는 기능

array([1, 3, 5, 7, 9])

## 2차원 배열 만들기

In [60]:
list2 = [[1, 2, 3], [4, 5, 6]]

In [61]:
arr2 = np.array(list2)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

# Numpy에서 제공하는 배열 정보 확인
- shape : 배열 크기 확인
- size : 총 요소 개수 확인
- ndim : 배열의 차원 확인
- dtype : 배열의 타입 확인

## 배열 크기 확인

In [62]:
arr2.shape

(2, 3)

## 배열의 총 요소 개수 확인

In [63]:
arr2.size

6

In [64]:
arr2.ndim

2

In [65]:
arr2.dtype

dtype('int64')

In [66]:
ls1=[1, 2, 3]
ls2=[4, 5, 6]

In [67]:
arr1 = np.array(ls1)
arr2 = np.array(ls2)

print(arr1)
print(arr2)
print(arr1 + arr2)
print(arr1 * arr2)

[1 2 3]
[4 5 6]
[5 7 9]
[ 4 10 18]


# Indexing & Slicing
- Indexing : 특정 요소를 가져올 때 사용
- Slicing : 특정 범위의 요소를 가져올 때 사용

In [68]:
arr1 = np.array([1, 3, 5, 7, 9, 11])

## 문제 1
- arr1에서 3, 9, 11을 각각 num1, num2, num3에 넣어서 출력

In [69]:
num1 = arr1[1]
num2 = arr1[4]
num3 = arr1[5]

In [70]:
print(num1)
print(num2)
print(num3)

3
9
11


## 문제 2
- 3부터 9까지 요소를 slicing을 사용하여 출력

In [71]:
print(arr1[1:5])

[3 5 7 9]


## 문제 3

In [72]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2[0][2], arr2[1][1])

3 5


In [73]:
arr2[:, 1:]

array([[2, 3],
       [5, 6]])

## 배열의 타입 변경
- astype : 배열 요소의 타입을 변경할 때 사용

In [75]:
arr2 = arr2.astype(float)
print(arr2)

[[1. 2. 3.]
 [4. 5. 6.]]


In [76]:
arr2 = arr2.astype(int)
print(arr2)

[[1 2 3]
 [4 5 6]]


In [79]:
list3 = []
for i in range(50):
    list3.append(i)

In [80]:
arr3 = np.array(list3)
print(arr3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


# arange
- 내가 원하는 범위만큼 배열을 생성해주는 기능

In [86]:
arr4 = np.arange(49)
print(arr4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]


In [92]:
arr5 = np.arange(50).reshape(5, 5,2)
arr5

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

## 문제 1

In [99]:
arr6 = np.arange(50).reshape(5,10)
arr6[1:4, 2:7]

array([[12, 13, 14, 15, 16],
       [22, 23, 24, 25, 26],
       [32, 33, 34, 35, 36]])

# 실습 1
- loadtxt : numpy에서 제공하는 txt파일을 읽을 때 사용

In [144]:
data = np.loadtxt('height_weight.txt', delimiter=',')

In [149]:
bmi_array = data[1, :] / ((data[0, :] / 100) ** 2)
bmi_array = np.round(bmi_array, 3)
bmi_array

array([21.372, 27.07 , 25.861, 24.207, 16.035, 20.145, 23.144, 21.697,
       23.62 , 25.592])

# Boolean 인덱싱
- True : 참 / False : 거짓
- True value만 출력

In [6]:
array1 = np.array([1, 2, 3])
array1[array1 >= 2]

array([2, 3])